# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Disabled until typer supports '|' in type hints
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.3.1
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py38-plus, --add-import, "from __future__ import annotations"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.220"
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: mypy-local
        name: mypy
        entry: mypy
        language: python
        types: [python]
        files: '.*\.py[i]?'
        exclude: ^tests/
        args: [--config-file, pyproject.toml, --ignore-missing-imports]
        # This is a bit of a hack, and might stop working in the future.
        # We should probably just specify the dependencies we need (PyYAML)
        additional_dependencies: [types-all]
