site_name: harbor-cli

repo_url: https://github.com/pederhan/harbor-cli
repo_name: pederhan/harbor-cli
edit_uri: edit/main/docs/

theme:
  name: "material"
  palette:
    scheme: slate
    primary: blue
    accent: orange
  language: en
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes

plugins:
  - search
  - autorefs
  - macros:
      on_error_fail: true
      include_dir: "docs/data"
      include_yaml:
        - commandlist: "docs/data/commands.yaml"
        - formats: "docs/data/formats.yaml"
  - mkdocstrings:
      watch:
        - harbor_cli
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            members_order: source
            docstring_section_style: table
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  # - configuration.md
  - "Configuration":
      - configuration/introduction.md
      - configuration/config-file.md
      - configuration/formats.md
  - "Usage":
      - usage/basic-usage.md
      - usage/commands.md
      - usage/options.md
      - usage/repl.md
      - usage/terminology.md
      # TODO: formats
  - "Reference":
      - "output":
          - "reference/output/index.md"
          - "reference/output/schema.md"

  - contributing.md
