[harbor]
url = ""
username = ""
secret = ""
basicauth = ""
credentials_file = ""

[logging]
enabled = true
structlog = false
level = "INFO"

[output]
format = "table"

[output.table]
description = false
max_depth = -1

[output.JSON]
indent = 2
sort_keys = true
